# Generated by Django 5.2.8 on 2025-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exam_examattempt_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='questions',
            field=models.ManyToManyField(blank=True, to='api.question'),
        ),
    ]
